name: Release Binaries

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0, v0.1.0

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude: # Exclude combinations that are not common or don't make sense
          - goos: windows
            goarch: arm64 # Windows on ARM64 is less common for CLI tools
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -v -o ip-lookup-${{ matrix.goos }}-${{ matrix.goarch }} .
          if [ "${{ matrix.goos }}" = "windows" ]; then
            mv ip-lookup-${{ matrix.goos }}-${{ matrix.goarch }} ip-lookup-${{ matrix.goos }}-${{ matrix.goarch }}.exe
          fi

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ip-lookup-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
          asset_name: ip-lookup-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Automated release for ${{ github.ref }}"

  build_and_push_docker:
    name: Build and Push Docker Image
    needs: build # Ensure this job runs after the 'build' job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required for pushing to GitHub Packages if used, or Docker Hub
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ali-issa/ip-lookup # Replace with your Docker Hub username/repo

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64 # Build for these platforms
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            RELEASE_VERSION=${{ github.ref_name }}
            BINARY_NAME=ip-lookup
          # Cache settings can be added here if needed
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
